// <auto-generated />
namespace SurveyGenerator.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addCUDproceduresforUSER : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addCUDproceduresforUSER));
        
        string IMigrationMetadata.Id
        {
            get { return "201905091129463_add CUD procedures for USER"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
